version: "3"

services:
  chrome:
    # ref: https://github.com/Zenika/alpine-chrome
    command: [chromium-browser, "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222", "--enable-logging", "--v=1"]
    image: zenika/alpine-chrome:latest
    networks:
      - default
    ports:
      - "9222:9222"
    security_opt:
      # ref: https://github.com/Zenika/alpine-chrome?tab=readme-ov-file#-the-best-with-seccomp
      - seccomp:config/chrome.jsonc

networks:
  default:

volumes:
  mongodb_data:
